---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: site1-l4-moonshot-sample
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./sites/apps/site1/L4
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-test
  targetNamespace: moonshot-sample
