---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-test
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./hosts/app/host1
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-test
  targetNamespace: default

