---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops-test
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: master
  url: https://github.com/buzzfrog/gitops-test

